---
- include_vars  : install-version.yml

- name          : Check Python3 installed
  stat          :
    path        : ~/.pyenv/versions/{{ python_version }}
  register      : installed_python3

- name          : Install Python3
  shell         : pyenv install {{ python_version }}
  when          : not installed_python3.stat.exists

- name          : Check created virtualenv
  stat          :
    path        : ~/.pyenv/versions/pyramid-sacrud
  register      : created_virtualenv

- name          : Create virtualenv
  shell         : pyenv virtualenv {{ python_version }} pyramid-sacrud
  when          : not created_virtualenv.stat.exists
