---
- name          : Install epel repository
  yum           :
    name        : epel-release

- name          : Install python-pip
  yum           :
    name        : python-pip

- name          : Upgrade pip
  pip           :
    name        : pip
    extra_args  : --upgrade
